#!/usr/bin/env bash
# Bash script that  installs the 'ufw' firewall.

apt-get update
apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw logging on
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw --force enable
