#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

apt-get -y update
apt-get -y install nginx

sudo sed -i "/^\s*location \/ {/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

sudo service nginx restart
